In [22]:
import numpy as np
import pandas as pd

df=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')

X=df.iloc[:,:-1]
X_test=df_test.iloc[:,:]
Y=df.iloc[:,-1]

###  To do KNN Imputing first we have to do LabelEncoding of data

In [23]:
cat=['City_Code','Accomodation_Type','Reco_Insurance_Type','Is_Spouse']
num=[i for i in X.columns if i not in cat]

In [24]:
X1=X.loc[:,cat]
X2=X.loc[:,num]

X1_test=X_test.loc[:,cat]
X2_test=X_test.loc[:,num]

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X1=X1.apply(le.fit_transform)

In [26]:
X1_test=X1_test.apply(LabelEncoder().fit_transform)

In [27]:
X2.nunique()

ID                         50882
Region_Code                 5316
Upper_Age                     58
Lower_Age                     60
Health Indicator               9
Holding_Policy_Duration       15
Holding_Policy_Type            4
Reco_Policy_Cat               22
Reco_Policy_Premium         6977
dtype: int64

In [28]:
unique_items1=X2['Health Indicator'].unique()
map_dict1={}
for i,j in enumerate(unique_items1):
    map_dict1[j]=i


In [29]:
map_dict1[np.nan]=np.nan

In [30]:
map_dict1

{'X1': 0,
 'X2': 1,
 nan: nan,
 'X4': 3,
 'X3': 4,
 'X6': 5,
 'X5': 6,
 'X8': 7,
 'X7': 8,
 'X9': 9}

In [31]:
X2['Health Indicator']=X2['Health Indicator'].map(map_dict1)

In [32]:
unique_items2=X2['Holding_Policy_Duration'].unique()
map_dict2={}
for i,j in enumerate(unique_items2):
    map_dict2[j]=i
map_dict2[np.nan]=np.nan
X2['Holding_Policy_Duration']=X2['Holding_Policy_Duration'].map(map_dict2)

In [47]:
unique_items3=X2['Holding_Policy_Type'].unique()
map_dict3={}
for i,j in enumerate(unique_items3):
    map_dict3[j]=i



In [45]:
map_dict3[NaN]=np.nan

NameError: name 'NaN' is not defined

In [53]:
map_dict3={3.0: 0, np.nan: np.nan, 1.0: 2, 4.0: 3, 2.0: 4}

In [54]:
X2['Holding_Policy_Type']=X2['Holding_Policy_Type'].map(map_dict3)

In [55]:
X2['Holding_Policy_Type'].unique()

array([ 0., nan,  2.,  3.,  4.])

In [56]:
X2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       50882 non-null  int64  
 1   Region_Code              50882 non-null  int64  
 2   Upper_Age                50882 non-null  int64  
 3   Lower_Age                50882 non-null  int64  
 4   Health Indicator         39191 non-null  float64
 5   Holding_Policy_Duration  30631 non-null  float64
 6   Holding_Policy_Type      30631 non-null  float64
 7   Reco_Policy_Cat          50882 non-null  int64  
 8   Reco_Policy_Premium      50882 non-null  float64
dtypes: float64(4), int64(5)
memory usage: 3.5 MB


In [57]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_Code            50882 non-null  int32
 1   Accomodation_Type    50882 non-null  int32
 2   Reco_Insurance_Type  50882 non-null  int32
 3   Is_Spouse            50882 non-null  int32
dtypes: int32(4)
memory usage: 795.2 KB


In [58]:
# Encoding the test set
X2_test['Health Indicator']=X2_test['Health Indicator'].map(map_dict1)
X2_test['Holding_Policy_Duration']=X2_test['Holding_Policy_Duration'].map(map_dict2)
X2_test['Holding_Policy_Type']=X2_test['Holding_Policy_Type'].map(map_dict3)


In [59]:
X=pd.concat([X1,X2],axis=1)
X_test=pd.concat([X1_test,X2_test],axis=1)

In [60]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   City_Code                50882 non-null  int32  
 1   Accomodation_Type        50882 non-null  int32  
 2   Reco_Insurance_Type      50882 non-null  int32  
 3   Is_Spouse                50882 non-null  int32  
 4   ID                       50882 non-null  int64  
 5   Region_Code              50882 non-null  int64  
 6   Upper_Age                50882 non-null  int64  
 7   Lower_Age                50882 non-null  int64  
 8   Health Indicator         39191 non-null  float64
 9   Holding_Policy_Duration  30631 non-null  float64
 10  Holding_Policy_Type      30631 non-null  float64
 11  Reco_Policy_Cat          50882 non-null  int64  
 12  Reco_Policy_Premium      50882 non-null  float64
dtypes: float64(4), int32(4), int64(5)
memory usage: 4.3 MB


In [61]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21805 entries, 0 to 21804
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   City_Code                21805 non-null  int32  
 1   Accomodation_Type        21805 non-null  int32  
 2   Reco_Insurance_Type      21805 non-null  int32  
 3   Is_Spouse                21805 non-null  int32  
 4   ID                       21805 non-null  int64  
 5   Region_Code              21805 non-null  int64  
 6   Upper_Age                21805 non-null  int64  
 7   Lower_Age                21805 non-null  int64  
 8   Health Indicator         16778 non-null  float64
 9   Holding_Policy_Duration  13202 non-null  float64
 10  Holding_Policy_Type      13202 non-null  float64
 11  Reco_Policy_Cat          21805 non-null  int64  
 12  Reco_Policy_Premium      21805 non-null  float64
dtypes: float64(4), int32(4), int64(5)
memory usage: 1.8 MB


In [62]:
X=X.drop(['ID'],axis=1)
X.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  Region_Code  \
0         22                  1                    0          0         3213   
1         31                  0                    1          0         1117   
2         31                  0                    0          0         3732   
3         16                  0                    1          0         4378   
4         34                  1                    0          0         2190   

   Upper_Age  Lower_Age  Health Indicator  Holding_Policy_Duration  \
0         36         36               0.0                      0.0   
1         75         22               1.0                      NaN   
2         32         32               NaN                      2.0   
3         52         48               0.0                      0.0   
4         44         44               1.0                      3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                  0.0               22              11628.0  
1                  NaN               22              30510.0  
2                  2.0               19               7450.0  
3                  0.0               19              17780.0  
4                  2.0               16              10404.0

In [63]:
X_test=X_test.drop(['ID'],axis=1)

### Before using knn imputer we have to do standard scaling. 

In [64]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)

In [65]:
X_test=pd.DataFrame(scaler.transform(X_test),columns=X_test.columns)

In [66]:
X.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  Region_Code  \
0   0.628571                1.0                  0.0        0.0     0.518650   
1   0.885714                0.0                  1.0        0.0     0.180203   
2   0.885714                0.0                  0.0        0.0     0.602454   
3   0.457143                0.0                  1.0        0.0     0.706766   
4   0.971429                1.0                  0.0        0.0     0.353464   

   Upper_Age  Lower_Age  Health Indicator  Holding_Policy_Duration  \
0   0.315789   0.338983          0.000000                 0.000000   
1   1.000000   0.101695          0.111111                      NaN   
2   0.245614   0.271186               NaN                 0.133333   
3   0.596491   0.542373          0.000000                 0.000000   
4   0.456140   0.474576          0.111111                 0.200000   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                  0.0         1.000000             0.227609  
1                  NaN         1.000000             0.687356  
2                  0.5         0.857143             0.125881  
3                  0.0         0.857143             0.377401  
4                  0.5         0.714286             0.197807

In [67]:
X_test.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  Region_Code  \
0   0.000000                0.0                  0.0        0.0     0.025028   
1   0.857143                0.0                  1.0        1.0     0.000969   
2   0.000000                1.0                  0.0        0.0     0.090909   
3   0.628571                1.0                  0.0        0.0     0.189892   
4   0.000000                0.0                  0.0        0.0     0.153399   

   Upper_Age  Lower_Age  Health Indicator  Holding_Policy_Duration  \
0   0.210526   0.237288               NaN                 0.800000   
1   0.894737   0.881356          0.000000                 0.200000   
2   0.175439   0.203390          0.444444                 0.533333   
3   0.087719   0.118644          0.444444                 0.200000   
4   1.000000   1.000000          0.444444                      NaN   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                 0.00         0.190476             0.235060  
1                 0.00         0.809524             0.728622  
2                 0.75         0.761905             0.169465  
3                 0.00         0.809524             0.165715  
4                  NaN         0.190476             0.493153

###  Using kNN imputer imputing the vales

In [68]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=5)
X=pd.DataFrame(imputer.fit_transform(X),columns=X.columns)

In [69]:
X_test=pd.DataFrame(imputer.transform(X_test),columns=X_test.columns)

In [70]:
X.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  Region_Code  \
0   0.628571                1.0                  0.0        0.0     0.518650   
1   0.885714                0.0                  1.0        0.0     0.180203   
2   0.885714                0.0                  0.0        0.0     0.602454   
3   0.457143                0.0                  1.0        0.0     0.706766   
4   0.971429                1.0                  0.0        0.0     0.353464   

   Upper_Age  Lower_Age  Health Indicator  Holding_Policy_Duration  \
0   0.315789   0.338983          0.000000                 0.000000   
1   1.000000   0.101695          0.111111                 0.106667   
2   0.245614   0.271186          0.244444                 0.133333   
3   0.596491   0.542373          0.000000                 0.000000   
4   0.456140   0.474576          0.111111                 0.200000   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                  0.0         1.000000             0.227609  
1                  0.5         1.000000             0.687356  
2                  0.5         0.857143             0.125881  
3                  0.0         0.857143             0.377401  
4                  0.5         0.714286             0.197807

In [71]:
X_test.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  Region_Code  \
0   0.000000                0.0                  0.0        0.0     0.025028   
1   0.857143                0.0                  1.0        1.0     0.000969   
2   0.000000                1.0                  0.0        0.0     0.090909   
3   0.628571                1.0                  0.0        0.0     0.189892   
4   0.000000                0.0                  0.0        0.0     0.153399   

   Upper_Age  Lower_Age  Health Indicator  Holding_Policy_Duration  \
0   0.210526   0.237288          0.222222                 0.800000   
1   0.894737   0.881356          0.000000                 0.200000   
2   0.175439   0.203390          0.444444                 0.533333   
3   0.087719   0.118644          0.444444                 0.200000   
4   1.000000   1.000000          0.444444                 0.440000   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                 0.00         0.190476             0.235060  
1                 0.00         0.809524             0.728622  
2                 0.75         0.761905             0.169465  
3                 0.00         0.809524             0.165715  
4                 0.10         0.190476             0.493153

### Now lets fit the model 

In [72]:
from sklearn.ensemble import RandomForestClassifier
reg=RandomForestClassifier(n_estimators=100,random_state=0,oob_score=True,max_depth=10)

In [73]:
reg.fit(X,Y)

RandomForestClassifier(max_depth=10, oob_score=True, random_state=0)

In [74]:
Y_pred=reg.predict(X)

In [75]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y,Y_pred)
cm

array([[38673,     0],
       [12172,    37]], dtype=int64)

In [76]:
reg.oob_score_

0.7599937109390354

In [77]:
reg.score(X,Y)

0.7607798435596085

In [78]:
Y_test_pred=reg.predict(X_test)

In [79]:
Y_test_pred[:5]

array([0, 0, 0, 0, 0], dtype=int64)

###  Submitting the results

In [80]:
len(Y_test_pred)

21805

In [81]:
len(df_test)

21805

In [82]:
id=pd.DataFrame(df_test.ID,columns=['ID'])

In [83]:
respo=pd.DataFrame(Y_test_pred,columns=['Response'])

In [84]:
pred=pd.concat([id,respo],axis=1)

In [85]:
pred.head()

ID  Response
0  50883         0
1  50884         0
2  50885         0
3  50886         0
4  50887         0

In [86]:
filename='Submission2.csv'
pred.to_csv(filename,index=False)