In [33]:
import numpy as np
import pandas as pd

df=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')

X=df.iloc[:,:-1]
X_test=df_test.iloc[:,:]
Y=df.iloc[:,-1]

In [34]:
X.head()

ID City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0   1        C3         3213            Rented          Individual         36   
1   2        C5         1117             Owned               Joint         75   
2   3        C5         3732             Owned          Individual         32   
3   4       C24         4378             Owned               Joint         52   
4   5        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                  3.0               22              11628.0  
1                  NaN               22              30510.0  
2                  1.0               19               7450.0  
3                  3.0               19              17780.0  
4                  1.0               16              10404.0

In [35]:
X_test.head()

ID City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  \
0  50883        C1          156             Owned          Individual   
1  50884        C4            7             Owned               Joint   
2  50885        C1          564            Rented          Individual   
3  50886        C3         1177            Rented          Individual   
4  50887        C1          951             Owned          Individual   

   Upper_Age  Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         30         30        No              NaN                     6.0   
1         69         68       Yes               X1                     3.0   
2         28         28        No               X3                     2.0   
3         23         23        No               X3                     3.0   
4         75         75        No               X3                     NaN   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  
0                  3.0                5              11934.0  
1                  3.0               18              32204.8  
2                  4.0               17               9240.0  
3                  3.0               18               9086.0  
4                  NaN                5              22534.0

In [36]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21805 entries, 0 to 21804
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       21805 non-null  int64  
 1   City_Code                21805 non-null  object 
 2   Region_Code              21805 non-null  int64  
 3   Accomodation_Type        21805 non-null  object 
 4   Reco_Insurance_Type      21805 non-null  object 
 5   Upper_Age                21805 non-null  int64  
 6   Lower_Age                21805 non-null  int64  
 7   Is_Spouse                21805 non-null  object 
 8   Health Indicator         16778 non-null  object 
 9   Holding_Policy_Duration  13202 non-null  object 
 10  Holding_Policy_Type      13202 non-null  float64
 11  Reco_Policy_Cat          21805 non-null  int64  
 12  Reco_Policy_Premium      21805 non-null  float64
dtypes: float64(2), int64(5), object(6)
memory usage: 2.2+ MB


## Missing Value treatment

In [7]:
# We have missing values in three feature.
'''
Health Indicator
Holding_Policy_Duration
Holding_Policy_Type

We have two MVT methods for now
1. Simple Imputer
2. kNN Imputer
'''

'\nHealth Indicator\nHolding_Policy_Duration\nHolding_Policy_Type\n\nWe have two MVT methods for now\n1. Simple Imputer\n2. kNN Imputer\n'

In [37]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X=imp.fit_transform(X)
col=X_test.columns
X=pd.DataFrame(X,columns=col)

In [38]:
X.head()

ID City_Code Region_Code Accomodation_Type Reco_Insurance_Type Upper_Age  \
0  1        C3        3213            Rented          Individual        36   
1  2        C5        1117             Owned               Joint        75   
2  3        C5        3732             Owned          Individual        32   
3  4       C24        4378             Owned               Joint        52   
4  5        C8        2190            Rented          Individual        44   

  Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0        36        No               X1                     14+   
1        22        No               X2                     1.0   
2        32        No               X1                     1.0   
3        48        No               X1                     14+   
4        44        No               X2                     3.0   

  Holding_Policy_Type Reco_Policy_Cat Reco_Policy_Premium  
0                   3              22               11628  
1                   3              22               30510  
2                   1              19                7450  
3                   3              19               17780  
4                   1              16               10404

In [39]:
#imputing the Test Dataset
X_test=imp.transform(X_test)
X_test=pd.DataFrame(X_test,columns=col)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       50882 non-null  object
 1   City_Code                50882 non-null  object
 2   Region_Code              50882 non-null  object
 3   Accomodation_Type        50882 non-null  object
 4   Reco_Insurance_Type      50882 non-null  object
 5   Upper_Age                50882 non-null  object
 6   Lower_Age                50882 non-null  object
 7   Is_Spouse                50882 non-null  object
 8   Health Indicator         50882 non-null  object
 9   Holding_Policy_Duration  50882 non-null  object
 10  Holding_Policy_Type      50882 non-null  object
 11  Reco_Policy_Cat          50882 non-null  object
 12  Reco_Policy_Premium      50882 non-null  object
dtypes: object(13)
memory usage: 5.0+ MB


In [44]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21805 entries, 0 to 21804
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   City_Code                21805 non-null  object
 1   Region_Code              21805 non-null  object
 2   Accomodation_Type        21805 non-null  object
 3   Reco_Insurance_Type      21805 non-null  object
 4   Upper_Age                21805 non-null  object
 5   Lower_Age                21805 non-null  object
 6   Is_Spouse                21805 non-null  object
 7   Health Indicator         21805 non-null  object
 8   Holding_Policy_Duration  21805 non-null  object
 9   Holding_Policy_Type      21805 non-null  object
 10  Reco_Policy_Cat          21805 non-null  object
 11  Reco_Policy_Premium      21805 non-null  object
dtypes: object(12)
memory usage: 2.0+ MB


In [42]:
X.head()

ID City_Code Region_Code Accomodation_Type Reco_Insurance_Type Upper_Age  \
0  1        C3        3213            Rented          Individual        36   
1  2        C5        1117             Owned               Joint        75   
2  3        C5        3732             Owned          Individual        32   
3  4       C24        4378             Owned               Joint        52   
4  5        C8        2190            Rented          Individual        44   

  Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0        36        No               X1                     14+   
1        22        No               X2                     1.0   
2        32        No               X1                     1.0   
3        48        No               X1                     14+   
4        44        No               X2                     3.0   

  Holding_Policy_Type Reco_Policy_Cat Reco_Policy_Premium  
0                   3              22               11628  
1                   3              22               30510  
2                   1              19                7450  
3                   3              19               17780  
4                   1              16               10404

In [45]:
cat=['City_Code','Accomodation_Type','Reco_Insurance_Type','Is_Spouse','Health Indicator','Holding_Policy_Duration']
num=[i for i in X.columns if i not in cat]

In [47]:
X1=X.loc[:,cat]
X2=X.loc[:,num]

X1_test=X_test.loc[:,cat]
X2_test=X_test.loc[:,num]



In [48]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X1=X1.apply(le.fit_transform)



In [58]:
X1_test=X1_test.apply(LabelEncoder().fit_transform)

In [59]:
[X1_test[i].unique() for i in X1_test.columns]

[array([ 0, 30, 22, 11,  4,  9,  7,  8,  2, 33, 13, 27,  5, 34,  3, 32,  1,
        35, 15, 25, 18,  6, 16, 12, 10, 31, 20, 23, 17, 21, 19, 26, 14, 29,
        28, 24]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 2, 1, 4, 3, 6, 5, 8, 7]),
 array([11,  8,  7,  0,  5, 10,  9,  3,  2, 12, 14,  4, 13,  6,  1])]

In [60]:
[X1[i].unique() for i in X1.columns]

[array([22, 31, 16, 34, 35,  0,  6, 20, 19, 33, 12, 17, 30, 11, 27,  1,  8,
         9,  7, 21, 26, 18, 10, 32,  3,  4,  2,  5, 14, 15, 13, 29, 25, 23,
        28, 24]),
 array([1, 0]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1, 3, 2, 5, 4, 7, 6, 8]),
 array([ 5,  0,  8, 10, 14,  6, 12,  7,  2,  1, 13, 11,  9,  4,  3])]

In [61]:
X1.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  \
0         22                  1                    0          0   
1         31                  0                    1          0   
2         31                  0                    0          0   
3         16                  0                    1          0   
4         34                  1                    0          0   

   Health Indicator  Holding_Policy_Duration  
0                 0                        5  
1                 1                        0  
2                 0                        0  
3                 0                        5  
4                 1                        8

In [62]:
X1_test.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  \
0          0                  0                    0          0   
1         30                  0                    1          1   
2          0                  1                    0          0   
3         22                  1                    0          0   
4          0                  0                    0          0   

   Health Indicator  Holding_Policy_Duration  
0                 0                       11  
1                 0                        8  
2                 2                        7  
3                 2                        8  
4                 2                        0

In [64]:
X=pd.concat([X1,X2],axis=1)

In [83]:
X_test=pd.concat([X1_test,X2_test],axis=1)

In [84]:
X.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  \
0         22                  1                    0          0   
1         31                  0                    1          0   
2         31                  0                    0          0   
3         16                  0                    1          0   
4         34                  1                    0          0   

   Health Indicator  Holding_Policy_Duration Region_Code Upper_Age Lower_Age  \
0                 0                        5        3213        36        36   
1                 1                        0        1117        75        22   
2                 0                        0        3732        32        32   
3                 0                        5        4378        52        48   
4                 1                        8        2190        44        44   

  Holding_Policy_Type Reco_Policy_Cat Reco_Policy_Premium  
0                   3              22               11628  
1                   3              22               30510  
2                   1              19                7450  
3                   3              19               17780  
4                   1              16               10404

In [85]:
X_test.head()

City_Code  Accomodation_Type  Reco_Insurance_Type  Is_Spouse  \
0          0                  0                    0          0   
1         30                  0                    1          1   
2          0                  1                    0          0   
3         22                  1                    0          0   
4          0                  0                    0          0   

   Health Indicator  Holding_Policy_Duration Region_Code Upper_Age Lower_Age  \
0                 0                       11         156        30        30   
1                 0                        8           7        69        68   
2                 2                        7         564        28        28   
3                 2                        8        1177        23        23   
4                 2                        0         951        75        75   

  Holding_Policy_Type Reco_Policy_Cat Reco_Policy_Premium  
0                   3               5               11934  
1                   3              18             32204.8  
2                   4              17                9240  
3                   3              18                9086  
4                   3               5               22534

In [68]:
Y.head()

0    0
1    0
2    1
3    0
4    0
Name: Response, dtype: int64

In [71]:
from sklearn.ensemble import RandomForestClassifier
reg=RandomForestClassifier(n_estimators=100,random_state=0,oob_score=True,max_depth=10)

In [72]:
reg.fit(X,Y)

RandomForestClassifier(max_depth=10, oob_score=True, random_state=0)

In [73]:
Y_pred=reg.predict(X)

In [74]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y,Y_pred)
cm

array([[38673,     0],
       [12167,    42]], dtype=int64)

In [75]:
reg.oob_score_

0.7600133642545498

In [76]:
reg.score(X,Y)

0.7608781101371801

In [87]:
Y_test_pred=reg.predict(X_test)

In [88]:
Y_test_pred[:5]

array([0, 0, 0, 0, 0], dtype=int64)

### Submitting the Y_test_pred 

In [89]:
len(Y_test_pred)

21805

In [90]:
len(df_test)

21805

In [93]:
id=pd.DataFrame(df_test.ID,columns=['ID'])

In [94]:
respo=pd.DataFrame(Y_test_pred,columns=['Response'])

In [95]:
pred=pd.concat([id,respo],axis=1)

In [96]:
pred.head()

ID  Response
0  50883         0
1  50884         0
2  50885         0
3  50886         0
4  50887         0

In [97]:
filename='Submission1.csv'
pred.to_csv(filename,index=False)